# Import Libraries

In [ ]:
import pandas as pd
import numpy as np

# Load Dataset

In [ ]:
df = pd.read_csv('Swiggy_Python_Messy_500.csv')

# Data Overview

In [ ]:
df.head(10)

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,Area,RestaurantID,RestaurantName,...,TotalAmount,OrderStatus,PaymentMode,PaymentStatus,PartnerName,VehicleType,DistanceKM,DeliveryTimeMin,FoodRating,DeliveryRating
0,ORD10397,30-Jan-24,CUST2295,Suresh Nair,M,31.0,Mumbai,Dadar,R009,The Bakers Oven,...,240,Cancelled,Wallet,Failed,Aarav Reddy,E-Bike,NaN,32.0,NaN,NaN
1,ORD10446,29-Dec-24,CUST2330,Priya Joshi,MALE,36.0,Bangalore,Jayanagar,R003,Dragon Wok,...,480,Delivered,DebitCard,Paid,Pooja Gupta,E-Bike,1.2,17.0,5.0,3.0
2,ORD10061,08/27/2024,CUST2016,Kiran Das,NaN,60.0,kolkata,Park Street,R007,Sushi Yama,...,840,Returned,WALLET,Refunded,Manoj Nair,Bicycle,13.4,77.0,NaN,NaN
3,ORD10116,30-06-2024 18:16,CUST2086,Karthik Bose,male,29.0,pune,Hinjewadi,R015,Chaat Corner,...,Rs.60.0,DELIVERED,wallet,Paid,Ravi Rao,Scooter,7.3,45.0,4.0,5.0
4,ORD10424,18-01-2024 12:18,CUST2224,Sunita Patel,m,32.0,Hyderabad,NaN,R015,Chaat Corner,...,210,cancelled,Credit Card,Failed,Reyansh Sharma,E-Bike,5.0,23.0,NaN,NaN
5,ORD10147,13-07-2024 08:40,CUST2107,Amit Chatterjee,NaN,24.0,Bangalore,Koramangala,R005,Burger Point,...,650,Returned,WALLET,Refunded,Kiran Desai,Scooter,6.4,43.0,NaN,NaN
6,ORD10411,17-06-2024 23:58,CUST2306,Sai Mukherjee,M,30.0,Mumbai,Bandra,R001,Biryani Blues,...,1400,DELIVERED,WALLET,Paid,Aarohi Patel,Bike,14.4,65.0,3.0,5.0
7,ORD10330,06-07-2024 08:03,CUST2241,NaN,f,54.0,Hyderabad,Secunderabad,R002,Pizza Palace,...,320,delivered,wallet,Paid,Pooja Gupta,E-Bike,6.5,39.0,5.0,4.0
8,ORD10286,08/30/2024,CUST2169,Aadhya Gupta,m,57.0,pune,Kothrud,R001,Biryani Blues,...,₹440.0,DELIVERED,CREDIT CARD,Paid,Anika Kapoor,Bicycle,2.2,23.0,5.0,5.0
9,ORD10200,03-04-2024 23:01,CUST2052,Krishna Chatterjee,Female,40.0,Kolkata,Salt Lake,R004,Punjabi Tadka,...,1040,Delivered,debit card,Paid,Sai Iyer,Scooter,12.5,67.0,3.0,3.0

In [ ]:
df.shape

(512, 26)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 512 entries, 0 to 511
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderID           512 non-null    object
 1   OrderDate         509 non-null    object
 2   CustomerID        512 non-null    object
 3   CustomerName      493 non-null    object
 4   Gender            487 non-null    object
 5   Age               485 non-null    float64
 6   City              494 non-null    object
 7   Area              497 non-null    object
 8   RestaurantID      512 non-null    object
 9   RestaurantName    512 non-null    object
 10  Cuisine           512 non-null    object
 11  RestaurantRating  491 non-null    float64
 12  ItemName          512 non-null    object
 13  CategoryName      512 non-null    object
 14  Quantity          512 non-null    int64
 15  UnitPrice         502 non-null    object
 16  TotalAmount       502 non-null    object
 17  OrderStatus       512 non-null    object
 18  PaymentMode       491 non-null    object
 19  PaymentStatus     512 non-null    object
 20  PartnerName       502 non-null    object
 21  VehicleType       512 non-null    object
 22  DistanceKM        497 non-null    float64
 23  DeliveryTimeMin   498 non-null    float64
 24  FoodRating        327 non-null    float64
 25  DeliveryRating    325 non-null    float64
dtypes: float64(6), int64(1), object(19)
memory usage: 104.1+ KB

In [ ]:
df.describe()

,Age,RestaurantRating,Quantity,DistanceKM,DeliveryTimeMin,FoodRating,DeliveryRating
count,485.000000,491.000000,512.000000,497.000000,498.000000,327.000000,325.000000
mean,38.931959,4.111405,3.013672,7.981891,46.343373,4.131498,4.166154
std,14.699662,0.763178,1.730866,11.686203,40.732239,1.011203,0.911226
min,-5.000000,-1.000000,-5.000000,-3.500000,-15.000000,-2.000000,-1.000000
25%,28.000000,4.000000,2.000000,3.800000,27.000000,4.000000,4.000000
50%,39.000000,4.100000,3.000000,7.500000,43.000000,4.000000,4.000000
75%,49.000000,4.300000,4.000000,11.200000,59.000000,5.000000,5.000000
max,150.000000,11.000000,5.000000,250.000000,500.000000,6.000000,6.000000

In [ ]:
df.isnull().sum()

OrderID               0
OrderDate             3
CustomerID            0
CustomerName         19
Gender               25
Age                  27
City                 18
Area                 15
RestaurantID          0
RestaurantName        0
Cuisine               0
RestaurantRating     21
ItemName              0
CategoryName          0
Quantity              0
UnitPrice            10
TotalAmount          10
OrderStatus           0
PaymentMode          21
PaymentStatus         0
PartnerName          10
VehicleType           0
DistanceKM           15
DeliveryTimeMin      14
FoodRating          185
DeliveryRating      187
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(8)

# Data Cleaning

## Change OrderDate DataType

In [ ]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'],dayfirst=True,errors='coerce')
df['OrderDate'] = df['OrderDate'].dt.strftime('%d-%m-%Y')

/tmp/ipykernel_29802/599978972.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['OrderDate'] = pd.to_datetime(df['OrderDate'],dayfirst=True,errors='coerce')

## Clean Inconsistent Values on Gender

In [ ]:
df['Gender'] = df['Gender'].str.lower()

df['Gender'] = df['Gender'].map({
    'm':'Male',
    'male':'Male',
    'f':'Female',
    'female':'Female'
})

In [ ]:
df.head(20)

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,Area,RestaurantID,RestaurantName,...,TotalAmount,OrderStatus,PaymentMode,PaymentStatus,PartnerName,VehicleType,DistanceKM,DeliveryTimeMin,FoodRating,DeliveryRating
0,ORD10397,30-01-2024,CUST2295,Suresh Nair,Male,31.0,Mumbai,Dadar,R009,The Bakers Oven,...,240,Cancelled,Wallet,Failed,Aarav Reddy,E-Bike,NaN,32.0,NaN,NaN
1,ORD10446,29-12-2024,CUST2330,Priya Joshi,Male,36.0,Bangalore,Jayanagar,R003,Dragon Wok,...,480,Delivered,DebitCard,Paid,Pooja Gupta,E-Bike,1.2,17.0,5.0,3.0
2,ORD10061,27-08-2024,CUST2016,Kiran Das,NaN,60.0,kolkata,Park Street,R007,Sushi Yama,...,840,Returned,WALLET,Refunded,Manoj Nair,Bicycle,13.4,77.0,NaN,NaN
3,ORD10116,30-06-2024,CUST2086,Karthik Bose,Male,29.0,pune,Hinjewadi,R015,Chaat Corner,...,Rs.60.0,DELIVERED,wallet,Paid,Ravi Rao,Scooter,7.3,45.0,4.0,5.0
4,ORD10424,18-01-2024,CUST2224,Sunita Patel,Male,32.0,Hyderabad,NaN,R015,Chaat Corner,...,210,cancelled,Credit Card,Failed,Reyansh Sharma,E-Bike,5.0,23.0,NaN,NaN
5,ORD10147,13-07-2024,CUST2107,Amit Chatterjee,NaN,24.0,Bangalore,Koramangala,R005,Burger Point,...,650,Returned,WALLET,Refunded,Kiran Desai,Scooter,6.4,43.0,NaN,NaN
6,ORD10411,17-06-2024,CUST2306,Sai Mukherjee,Male,30.0,Mumbai,Bandra,R001,Biryani Blues,...,1400,DELIVERED,WALLET,Paid,Aarohi Patel,Bike,14.4,65.0,3.0,5.0
7,ORD10330,06-07-2024,CUST2241,NaN,Female,54.0,Hyderabad,Secunderabad,R002,Pizza Palace,...,320,delivered,wallet,Paid,Pooja Gupta,E-Bike,6.5,39.0,5.0,4.0
8,ORD10286,30-08-2024,CUST2169,Aadhya Gupta,Male,57.0,pune,Kothrud,R001,Biryani Blues,...,₹440.0,DELIVERED,CREDIT CARD,Paid,Anika Kapoor,Bicycle,2.2,23.0,5.0,5.0
9,ORD10200,03-04-2024,CUST2052,Krishna Chatterjee,Female,40.0,Kolkata,Salt Lake,R004,Punjabi Tadka,...,1040,Delivered,debit card,Paid,Sai Iyer,Scooter,12.5,67.0,3.0,3.0
10,ORD10340,19-12-2024,CUST2249,Kiran Sharma,Female,36.0,NaN,Saket,R003,Dragon Wok,...,140,DELIVERED,Debit Card,Paid,Suresh Kumar,Scooter,4.7,31.0,5.0,4.0
11,ORD10140,16-06-2024,CUST2092,Vikram Malhotra,Female,45.0,Chennai,Anna Nagar,R012,Noodle Story,...,630,DELIVERED,upi,Paid,Nikhil Malhotra,Scooter,7.1,NaN,3.0,4.0
12,ORD10395,02-02-2024,CUST2293,Priya Menon,Male,55.0,Bangalore,Electronic City,R006,South Spice,...,70,delivered,Debit Card,Paid,Lakshmi Verma,Scooter,1.6,13.0,4.0,5.0
13,ORD10324,28-12-2024,CUST2237,Aadhya Das,Male,NaN,PUNE,Kharadi,R005,Burger Point,...,180,Delivered,Wallet,Paid,Ishaan Joshi,Bike,7.3,46.0,3.0,4.0
14,ORD10175,17-08-2024,CUST2012,Aditya Sharma,Female,39.0,KOLKATA,Park Street,R015,Chaat Corner,...,200,Returned,debit card,Refunded,Vivaan Singh,Bike,8.0,47.0,NaN,NaN
15,ORD10268,24-03-2024,CUST2108,Rahul Iyer,Female,37.0,Bengaluru,HSR Layout,R003,Dragon Wok,...,700,DELIVERED,Debit Card,Paid,Pooja Gupta,Scooter,8.8,49.0,4.0,3.0
16,ORD10238,19-08-2024,CUST2178,Deepak Rao,Male,52.0,Hyderabad,Madhapur,R012,Noodle Story,...,1050,DELIVERED,CREDIT CARD,Paid,Aarav Reddy,Bike,8.7,46.0,3.0,5.0
17,ORD10136,29-11-2024,CUST2099,Aditya Iyer,Male,43.0,Delhi,Connaught Place,R009,The Bakers Oven,...,90,returned,UPI,Refunded,Vivaan Singh,E-Bike,12.8,69.0,NaN,NaN
18,ORD10130,19-04-2024,CUST2094,Deepak Gupta,Male,39.0,NaN,Andheri,R004,Punjabi Tadka,...,260,RETURNED,CASH ON DELIVERY,Refunded,Suresh Kumar,Bicycle,NaN,33.0,NaN,NaN
19,ORD10384,16-02-2024,CUST2041,Aditya Das,Male,21.0,Mumbai,Dadar,R012,Noodle Story,...,Rs.160.0,Delivered,cash on delivery,Paid,Krishna Chatterjee,Bicycle,2.3,21.0,3.0,5.0

In [ ]:
df['City'].unique()

array([' Mumbai ', 'Bangalore', 'kolkata', 'pune', 'Hyderabad', 'Mumbai',
       ' Kolkata ', nan, ' Chennai ', 'PUNE', 'KOLKATA', 'Bengaluru',
       'Delhi', 'Chennai', 'Kolkata', 'DELHI', 'MUMBAI', 'CHENNAI',
       'Pune', 'BANGALORE', 'hyderabad', 'delhi', 'bangalore', 'mumbai',
       ' Pune ', ' Bangalore ', 'HYDERABAD', ' Delhi ', 'chennai',
       ' Hyderabad '], dtype=object)

## Column City

In [ ]:
df['City'] = df['City'].str.lower().str.strip()

df['City'] = df['City'].map({
    "mumbai":"Mumbai",
    "bangalore":"Bangalore",
    "bengaluru":"Bangalore",
    'kolkata':"Kolkata",
    'pune':'Pune',
    'hyderabad':'Hyderabad',
    'chennai':'Chennai',
    'delhi':'Delhi'
})

In [ ]:
df.head(20)

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,Area,RestaurantID,RestaurantName,...,TotalAmount,OrderStatus,PaymentMode,PaymentStatus,PartnerName,VehicleType,DistanceKM,DeliveryTimeMin,FoodRating,DeliveryRating
0,ORD10397,30-01-2024,CUST2295,Suresh Nair,Male,31.0,Mumbai,Dadar,R009,The Bakers Oven,...,240,Cancelled,Wallet,Failed,Aarav Reddy,E-Bike,NaN,32.0,NaN,NaN
1,ORD10446,29-12-2024,CUST2330,Priya Joshi,Male,36.0,Bangalore,Jayanagar,R003,Dragon Wok,...,480,Delivered,DebitCard,Paid,Pooja Gupta,E-Bike,1.2,17.0,5.0,3.0
2,ORD10061,27-08-2024,CUST2016,Kiran Das,NaN,60.0,Kolkata,Park Street,R007,Sushi Yama,...,840,Returned,WALLET,Refunded,Manoj Nair,Bicycle,13.4,77.0,NaN,NaN
3,ORD10116,30-06-2024,CUST2086,Karthik Bose,Male,29.0,Pune,Hinjewadi,R015,Chaat Corner,...,Rs.60.0,DELIVERED,wallet,Paid,Ravi Rao,Scooter,7.3,45.0,4.0,5.0
4,ORD10424,18-01-2024,CUST2224,Sunita Patel,Male,32.0,Hyderabad,NaN,R015,Chaat Corner,...,210,cancelled,Credit Card,Failed,Reyansh Sharma,E-Bike,5.0,23.0,NaN,NaN
5,ORD10147,13-07-2024,CUST2107,Amit Chatterjee,NaN,24.0,Bangalore,Koramangala,R005,Burger Point,...,650,Returned,WALLET,Refunded,Kiran Desai,Scooter,6.4,43.0,NaN,NaN
6,ORD10411,17-06-2024,CUST2306,Sai Mukherjee,Male,30.0,Mumbai,Bandra,R001,Biryani Blues,...,1400,DELIVERED,WALLET,Paid,Aarohi Patel,Bike,14.4,65.0,3.0,5.0
7,ORD10330,06-07-2024,CUST2241,NaN,Female,54.0,Hyderabad,Secunderabad,R002,Pizza Palace,...,320,delivered,wallet,Paid,Pooja Gupta,E-Bike,6.5,39.0,5.0,4.0
8,ORD10286,30-08-2024,CUST2169,Aadhya Gupta,Male,57.0,Pune,Kothrud,R001,Biryani Blues,...,₹440.0,DELIVERED,CREDIT CARD,Paid,Anika Kapoor,Bicycle,2.2,23.0,5.0,5.0
9,ORD10200,03-04-2024,CUST2052,Krishna Chatterjee,Female,40.0,Kolkata,Salt Lake,R004,Punjabi Tadka,...,1040,Delivered,debit card,Paid,Sai Iyer,Scooter,12.5,67.0,3.0,3.0
10,ORD10340,19-12-2024,CUST2249,Kiran Sharma,Female,36.0,NaN,Saket,R003,Dragon Wok,...,140,DELIVERED,Debit Card,Paid,Suresh Kumar,Scooter,4.7,31.0,5.0,4.0
11,ORD10140,16-06-2024,CUST2092,Vikram Malhotra,Female,45.0,Chennai,Anna Nagar,R012,Noodle Story,...,630,DELIVERED,upi,Paid,Nikhil Malhotra,Scooter,7.1,NaN,3.0,4.0
12,ORD10395,02-02-2024,CUST2293,Priya Menon,Male,55.0,Bangalore,Electronic City,R006,South Spice,...,70,delivered,Debit Card,Paid,Lakshmi Verma,Scooter,1.6,13.0,4.0,5.0
13,ORD10324,28-12-2024,CUST2237,Aadhya Das,Male,NaN,Pune,Kharadi,R005,Burger Point,...,180,Delivered,Wallet,Paid,Ishaan Joshi,Bike,7.3,46.0,3.0,4.0
14,ORD10175,17-08-2024,CUST2012,Aditya Sharma,Female,39.0,Kolkata,Park Street,R015,Chaat Corner,...,200,Returned,debit card,Refunded,Vivaan Singh,Bike,8.0,47.0,NaN,NaN
15,ORD10268,24-03-2024,CUST2108,Rahul Iyer,Female,37.0,Bangalore,HSR Layout,R003,Dragon Wok,...,700,DELIVERED,Debit Card,Paid,Pooja Gupta,Scooter,8.8,49.0,4.0,3.0
16,ORD10238,19-08-2024,CUST2178,Deepak Rao,Male,52.0,Hyderabad,Madhapur,R012,Noodle Story,...,1050,DELIVERED,CREDIT CARD,Paid,Aarav Reddy,Bike,8.7,46.0,3.0,5.0
17,ORD10136,29-11-2024,CUST2099,Aditya Iyer,Male,43.0,Delhi,Connaught Place,R009,The Bakers Oven,...,90,returned,UPI,Refunded,Vivaan Singh,E-Bike,12.8,69.0,NaN,NaN
18,ORD10130,19-04-2024,CUST2094,Deepak Gupta,Male,39.0,NaN,Andheri,R004,Punjabi Tadka,...,260,RETURNED,CASH ON DELIVERY,Refunded,Suresh Kumar,Bicycle,NaN,33.0,NaN,NaN
19,ORD10384,16-02-2024,CUST2041,Aditya Das,Male,21.0,Mumbai,Dadar,R012,Noodle Story,...,Rs.160.0,Delivered,cash on delivery,Paid,Krishna Chatterjee,Bicycle,2.3,21.0,3.0,5.0

## TotalAmount

In [ ]:
df['TotalAmount'] = (df['TotalAmount']
    .astype(str)
    .str.replace("Rs.","",regex=False)
    .str.replace("₹","",regex=False)
    .str.strip()
    .astype(float)
)

In [ ]:
df['TotalAmount'].dtype

dtype('float64')

In [ ]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'Gender', 'Age',
       'City', 'Area', 'RestaurantID', 'RestaurantName', 'Cuisine',
       'RestaurantRating', 'ItemName', 'CategoryName', 'Quantity', 'UnitPrice',
       'TotalAmount', 'OrderStatus', 'PaymentMode', 'PaymentStatus',
       'PartnerName', 'VehicleType', 'DistanceKM', 'DeliveryTimeMin',
       'FoodRating', 'DeliveryRating'],
      dtype='object')

## Cuisine

In [ ]:
df['Cuisine'].unique()

array(['Bakery', 'Chinese', 'Japanese', 'Street Food', 'Fast Food',
       'Biryani', 'Italian', 'North Indian', 'South Indian', 'chinese',
       'Itallian', 'Salads', 'Desserts', 'Mughlai', 'Mexican',
       'north indian', 'italian', 'Chineese', 'North-Indian'],
      dtype=object)

In [ ]:
df['Cuisine'] = df['Cuisine'].str.lower()
df['Cuisine'] = df['Cuisine'].map({
    "bakery":"Bakery",
    "chinese":"Chinese",
    "japanese":"Japanese",
    "street food":"Street Food",
    "fast food":"Fast Food",
    "briyani":"Briyani",
    'italian':"Italian",
    'north indian':'North Indian',
    'south indian':"South Indian",
    'salads':'Salads',
    'desserts':"Desserts",
    'mughlai':'Mughlai',
    'mexican':'Mexican',
    'north-indian':"North Indian"

})

In [ ]:
df['Cuisine'].unique()

array(['Bakery', 'Chinese', 'Japanese', 'Street Food', 'Fast Food', nan,
       'Italian', 'North Indian', 'South Indian', 'Salads', 'Desserts',
       'Mughlai', 'Mexican'], dtype=object)

## UnitPrice

In [ ]:
df['UnitPrice'].unique()

array(['80', '160', '280', 'Rs.60.0', '70', 'Rs.130.0', 'Rs.320.0', '220',
       '260', '140', '210', 'Rs.70.0', '90', 'Rs.50.0', '240', '320',
       'Rs.90.0', '100', '350', '130', '₹130.0', '₹220.0', '180',
       '₹140.0', '120', '₹70.0', '₹210.0', '250', '₹260.0', 'Rs.120.0',
       'Rs.220.0', 'Rs.210.0', 'Rs.180.0', 'Rs.110.0', nan, '50', '₹90.0',
       'Rs.100.0', '150', '₹350.0', '110', '₹60.0', 'Rs.160.0', '₹150.0',
       'Rs.150.0', 'Rs.140.0', '₹280.0', '₹180.0', '₹160.0', '60',
       'Rs.280.0', '₹320.0', '₹100.0', '₹110.0', 'Rs.250.0', 'Rs.240.0',
       'Rs.260.0'], dtype=object)

In [ ]:
df['UnitPrice'] = (
    df['UnitPrice']
    .astype(str)
    .str.replace("Rs.","",regex=False)
    .str.replace("₹","",regex=False)
    .str.strip()
    .astype(float)
)

## OrderStatus

In [ ]:
df['OrderStatus'] = df['OrderStatus'].str.lower()

df['OrderStatus'] = df['OrderStatus'].map({
    "delivered":"Delivered",
    "returned":"Returned",
    "cancelled":"Cancelled"
})

In [ ]:
df['OrderStatus'].unique()

array(['Cancelled', 'Delivered', 'Returned'], dtype=object)

## PaymentMode

In [ ]:
df['PaymentMode'] = df['PaymentMode'].str.lower()

In [ ]:
df[df['PaymentMode']=="-"] = np.nan

In [ ]:
df['PaymentMode'].unique()

array(['wallet', 'debitcard', 'credit card', 'debit card', 'upi',
       'cash on delivery', 'cashondelivery', nan, 'creditcard'],
      dtype=object)

In [ ]:
df['PaymentMode'] = df['PaymentMode'].str.lower()
df['PaymentMode'] = df['PaymentMode'].map({
    "wallet":"Wallet",
    "debitcard":"DebitCard",
    "credit card":"CreditCard",
    'upi':'UPI',
    'cash on delivery':'Cash On Delivery',
    'creditcard':'CreditCard',
    'debit card':'DebitCard',
    'cashondelivery':"Cash On Delivery"
})

## Clean RestaurantName

In [ ]:
df['RestaurantName']=df['RestaurantName'].str.strip()

/tmp/ipykernel_29802/1548715299.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['RestaurantName']=df['RestaurantName'].str.strip()

## Handle Missing Values

### Numerical columns

In [ ]:
num_cols = df.select_dtypes(include='number').columns

for i in num_cols:
  if -0.5<= df[i].skew() <=0.5:
    df[i] = df[i].fillna(df[i].mean())
  else:
    df[i] = df[i].fillna(df[i].median())

### Categorical columns

In [ ]:
cat_cols = df.select_dtypes(include='object').columns

for i in cat_cols:
  df[i] = df[i].fillna(df[i].mode()[0])

In [ ]:
df.isnull().sum()

OrderID             0
OrderDate           0
CustomerID          0
CustomerName        0
Gender              0
Age                 0
City                0
Area                0
RestaurantID        0
RestaurantName      0
Cuisine             0
RestaurantRating    0
ItemName            0
CategoryName        0
Quantity            0
UnitPrice           0
TotalAmount         0
OrderStatus         0
PaymentMode         0
PaymentStatus       0
PartnerName         0
VehicleType         0
DistanceKM          0
DeliveryTimeMin     0
FoodRating          0
DeliveryRating      0
dtype: int64

## Duplicate Values

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

## Final checks

In [ ]:
df.head(10)

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,Area,RestaurantID,RestaurantName,...,TotalAmount,OrderStatus,PaymentMode,PaymentStatus,PartnerName,VehicleType,DistanceKM,DeliveryTimeMin,FoodRating,DeliveryRating
0,ORD10397,30-01-2024,CUST2295,Suresh Nair,Male,31.0,Mumbai,Dadar,R009,The Bakers Oven,...,240.0,Cancelled,Wallet,Failed,Aarav Reddy,E-Bike,7.5,32.0,4.0,4.0
1,ORD10446,29-12-2024,CUST2330,Priya Joshi,Male,36.0,Bangalore,Jayanagar,R003,Dragon Wok,...,480.0,Delivered,DebitCard,Paid,Pooja Gupta,E-Bike,1.2,17.0,5.0,3.0
2,ORD10061,27-08-2024,CUST2016,Kiran Das,Male,60.0,Kolkata,Park Street,R007,Sushi Yama,...,840.0,Returned,Wallet,Refunded,Manoj Nair,Bicycle,13.4,77.0,4.0,4.0
3,ORD10116,30-06-2024,CUST2086,Karthik Bose,Male,29.0,Pune,Hinjewadi,R015,Chaat Corner,...,60.0,Delivered,Wallet,Paid,Ravi Rao,Scooter,7.3,45.0,4.0,5.0
4,ORD10424,18-01-2024,CUST2224,Sunita Patel,Male,32.0,Hyderabad,Kharadi,R015,Chaat Corner,...,210.0,Cancelled,CreditCard,Failed,Reyansh Sharma,E-Bike,5.0,23.0,4.0,4.0
5,ORD10147,13-07-2024,CUST2107,Amit Chatterjee,Male,24.0,Bangalore,Koramangala,R005,Burger Point,...,650.0,Returned,Wallet,Refunded,Kiran Desai,Scooter,6.4,43.0,4.0,4.0
6,ORD10411,17-06-2024,CUST2306,Sai Mukherjee,Male,30.0,Mumbai,Bandra,R001,Biryani Blues,...,1400.0,Delivered,Wallet,Paid,Aarohi Patel,Bike,14.4,65.0,3.0,5.0
7,ORD10330,06-07-2024,CUST2241,Amit Malhotra,Female,54.0,Hyderabad,Secunderabad,R002,Pizza Palace,...,320.0,Delivered,Wallet,Paid,Pooja Gupta,E-Bike,6.5,39.0,5.0,4.0
8,ORD10286,30-08-2024,CUST2169,Aadhya Gupta,Male,57.0,Pune,Kothrud,R001,Biryani Blues,...,440.0,Delivered,CreditCard,Paid,Anika Kapoor,Bicycle,2.2,23.0,5.0,5.0
9,ORD10200,03-04-2024,CUST2052,Krishna Chatterjee,Female,40.0,Kolkata,Salt Lake,R004,Punjabi Tadka,...,1040.0,Delivered,DebitCard,Paid,Sai Iyer,Scooter,12.5,67.0,3.0,3.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 503 entries, 0 to 511
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderID           503 non-null    object
 1   OrderDate         503 non-null    object
 2   CustomerID        503 non-null    object
 3   CustomerName      503 non-null    object
 4   Gender            503 non-null    object
 5   Age               503 non-null    float64
 6   City              503 non-null    object
 7   Area              503 non-null    object
 8   RestaurantID      503 non-null    object
 9   RestaurantName    503 non-null    object
 10  Cuisine           503 non-null    object
 11  RestaurantRating  503 non-null    float64
 12  ItemName          503 non-null    object
 13  CategoryName      503 non-null    object
 14  Quantity          503 non-null    float64
 15  UnitPrice         503 non-null    float64
 16  TotalAmount       503 non-null    float64
 17  OrderStatus       503 non-null    object
 18  PaymentMode       503 non-null    object
 19  PaymentStatus     503 non-null    object
 20  PartnerName       503 non-null    object
 21  VehicleType       503 non-null    object
 22  DistanceKM        503 non-null    float64
 23  DeliveryTimeMin   503 non-null    float64
 24  FoodRating        503 non-null    float64
 25  DeliveryRating    503 non-null    float64
dtypes: float64(9), object(17)
memory usage: 106.1+ KB

In [ ]:
for i in cat_cols:
  print(i,df[i].unique())

OrderID ['ORD10397' 'ORD10446' 'ORD10061' 'ORD10116' 'ORD10424' 'ORD10147'
 'ORD10411' 'ORD10330' 'ORD10286' 'ORD10200' 'ORD10340' 'ORD10140'
 'ORD10395' 'ORD10324' 'ORD10175' 'ORD10268' 'ORD10238' 'ORD10136'
 'ORD10130' 'ORD10384' 'ORD10054' 'ORD10229' 'ORD10312' 'ORD10485'
 'ORD10430' 'ORD10464' 'ORD10058' 'ORD10445' 'ORD10201' 'ORD10271'
 'ORD10345' 'ORD10280' 'ORD10256' 'ORD10451' 'ORD10377' 'ORD10355'
 'ORD10320' 'ORD10248' 'ORD10408' 'ORD10370' 'ORD10343' 'ORD10040'
 'ORD10470' 'ORD10154' 'ORD10293' 'ORD10471' 'ORD10366' 'ORD10221'
 'ORD10500' 'ORD10233' 'ORD10088' 'ORD10071' 'ORD10492' 'ORD10180'
 'ORD10166' 'ORD10212' 'ORD10215' 'ORD10156' 'ORD10427' 'ORD10017'
 'ORD10118' 'ORD10461' 'ORD10348' 'ORD10089' 'ORD10326' 'ORD10231'
 'ORD10436' 'ORD10388' 'ORD10420' 'ORD10244' 'ORD10197' 'ORD10171'
 'ORD10005' 'ORD10416' 'ORD10478' 'ORD10138' 'ORD10027' 'ORD10084'
 'ORD10279' 'ORD10291' 'ORD10105' 'ORD10045' 'ORD10021' 'ORD10477'
 'ORD10174' 'ORD10272' 'ORD10433' 'ORD10062' 'ORD10034' 'ORD10220'
 'ORD10267' 'ORD10192' 'ORD10124' 'ORD10251' 'ORD10487' 'ORD10114'
 'ORD10144' 'ORD10087' 'ORD10259' 'ORD10432' 'ORD10289' 'ORD10008'
 'ORD10387' 'ORD10497' 'ORD10476' 'ORD10399' 'ORD10163' 'ORD10137'
 'ORD10022' 'ORD10015' 'ORD10379' 'ORD10346' 'ORD10057' 'ORD10273'
 'ORD10170' 'ORD10189' 'ORD10496' 'ORD10499' 'ORD10341' 'ORD10095'
 'ORD10405' 'ORD10020' 'ORD10308' 'ORD10075' 'ORD10032' 'ORD10484'
 'ORD10318' 'ORD10472' 'ORD10129' 'ORD10217' 'ORD10298' 'ORD10252'
 'ORD10122' 'ORD10295' 'ORD10452' 'ORD10260' 'ORD10219' 'ORD10038'
 'ORD10382' 'ORD10211' 'ORD10325' 'ORD10190' 'ORD10102' 'ORD10055'
 'ORD10056' 'ORD10465' 'ORD10042' 'ORD10204' 'ORD10145' 'ORD10297'
 'ORD10337' 'ORD10176' 'ORD10353' 'ORD10425' 'ORD10475' 'ORD10349'
 'ORD10258' 'ORD10354' 'ORD10050' 'ORD10125' 'ORD10381' 'ORD10012'
 'ORD10407' 'ORD10306' 'ORD10208' 'ORD10151' 'ORD10241' 'ORD10013'
 'ORD10230' 'ORD10240' 'ORD10103' 'ORD10159' 'ORD10205' 'ORD10203'
 'ORD10185' 'ORD10029' 'ORD10181' 'ORD10107' 'ORD10365' 'ORD10450'
 'ORD10383' 'ORD10282' 'ORD10083' 'ORD10191' 'ORD10053' 'ORD10135'
 'ORD10131' 'ORD10202' 'ORD10099' 'ORD10275' 'ORD10263' 'ORD10235'
 'ORD10373' 'ORD10422' 'ORD10218' 'ORD10127' 'ORD10296' 'ORD10106'
 'ORD10317' 'ORD10421' 'ORD10010' 'ORD10104' 'ORD10213' 'ORD10415'
 'ORD10078' 'ORD10278' 'ORD10009' 'ORD10453' 'ORD10199' 'ORD10003'
 'ORD10334' 'ORD10222' 'ORD10332' 'ORD10394' 'ORD10269' 'ORD10198'
 'ORD10026' 'ORD10285' 'ORD10299' 'ORD10196' 'ORD10468' 'ORD10351'
 'ORD10051' 'ORD10447' 'ORD10086' 'ORD10160' 'ORD10165' 'ORD10426'
 'ORD10023' 'ORD10063' 'ORD10456' 'ORD10100' 'ORD10070' 'ORD10444'
 'ORD10187' 'ORD10403' 'ORD10183' 'ORD10350' 'ORD10406' 'ORD10113'
 'ORD10309' 'ORD10206' 'ORD10096' 'ORD10152' 'ORD10184' 'ORD10467'
 'ORD10305' 'ORD10030' 'ORD10390' 'ORD10358' 'ORD10239' 'ORD10473'
 'ORD10311' 'ORD10480' 'ORD10117' 'ORD10277' 'ORD10316' 'ORD10369'
 'ORD10047' 'ORD10004' 'ORD10319' 'ORD10236' 'ORD10031' 'ORD10155'
 'ORD10292' 'ORD10052' 'ORD10037' 'ORD10098' 'ORD10283' 'ORD10014'
 'ORD10164' 'ORD10059' 'ORD10064' 'ORD10234' 'ORD10463' 'ORD10380'
 'ORD10486' 'ORD10266' 'ORD10495' 'ORD10079' 'ORD10046' 'ORD10158'
 'ORD10025' 'ORD10321' 'ORD10257' 'ORD10429' 'ORD10347' 'ORD10428'
 'ORD10290' 'ORD10356' 'ORD10323' 'ORD10123' 'ORD10067' 'ORD10195'
 'ORD10178' 'ORD10207' 'ORD10128' 'ORD10352' 'ORD10310' 'ORD10342'
 'ORD10001' 'ORD10227' 'ORD10462' 'ORD10454' 'ORD10250' 'ORD10109'
 'ORD10194' 'ORD10006' 'ORD10261' 'ORD10455' 'ORD10314' 'ORD10414'
 'ORD10448' 'ORD10060' 'ORD10048' 'ORD10303' 'ORD10028' 'ORD10121'
 'ORD10287' 'ORD10376' 'ORD10167' 'ORD10313' 'ORD10378' 'ORD10210'
 'ORD10359' 'ORD10223' 'ORD10300' 'ORD10214' 'ORD10396' 'ORD10360'
 'ORD10458' 'ORD10043' 'ORD10400' 'ORD10459' 'ORD10435' 'ORD10077'
 'ORD10401' 'ORD10460' 'ORD10413' 'ORD10392' 'ORD10437' 'ORD10367'
 'ORD10153' 'ORD10033' 'ORD10016' 'ORD10108' 'ORD10498' 'ORD10148'
 'ORD10255' 'ORD10438' 'ORD10036' 'ORD10226' 'ORD10173' 'ORD10385'
 'ORD10018' 'ORD10344' 'ORD10157' 'ORD10494' 'ORD10391' 'ORD10482'
 'ORD10490' 'ORD10431' 'ORD10372' 'ORD10209' 'ORD10065' 'ORD10011'
 'ORD10443' 'ORD10112' 'ORD10474' 'ORD10457' 'ORD10398' 'ORD10094'
 'ORD10483' 'ORD10294' 'ORD10262' 'ORD10101' 'ORD10168' 'ORD10066'
 'ORD10315' 'ORD10242' 'ORD10361' 'ORD10419' 'ORD10007' 'ORD10150'
 'ORD10488' 'ORD10402' 'ORD10368' 'ORD10481' 'ORD10363' 'ORD10149'
 'ORD10404' 'ORD10434' 'ORD10253' 'ORD10322' 'ORD10186' 'ORD10142'
 'ORD10133' 'ORD10357' 'ORD10119' 'ORD10245' 'ORD10288' 'ORD10375'
 'ORD10120' 'ORD10491' 'ORD10039' 'ORD10441' 'ORD10307' 'ORD10085'
 'ORD10225' 'ORD10073' 'ORD10076' 'ORD10362' 'ORD10489' 'ORD10418'
 'ORD10265' 'ORD10041' 'ORD10439' 'ORD10111' 'ORD10304' 'ORD10466'
 'ORD10049' 'ORD10019' 'ORD10044' 'ORD10274' 'ORD10423' 'ORD10091'
 'ORD10374' 'ORD10276' 'ORD10335' 'ORD10161' 'ORD10115' 'ORD10329'
 'ORD10069' 'ORD10216' 'ORD10393' 'ORD10132' 'ORD10002' 'ORD10188'
 'ORD10228' 'ORD10179' 'ORD10328' 'ORD10182' 'ORD10134' 'ORD10224'
 'ORD10249' 'ORD10284' 'ORD10169' 'ORD10449' 'ORD10336' 'ORD10264'
 'ORD10143' 'ORD10246' 'ORD10301' 'ORD10442' 'ORD10139' 'ORD10364'
 'ORD10090' 'ORD10479' 'ORD10412' 'ORD10024' 'ORD10097' 'ORD10080'
 'ORD10493' 'ORD10193' 'ORD10243' 'ORD10371' 'ORD10172' 'ORD10327'
 'ORD10068' 'ORD10146' 'ORD10409' 'ORD10082' 'ORD10469' 'ORD10232'
 'ORD10331' 'ORD10386' 'ORD10141' 'ORD10035' 'ORD10389' 'ORD10126'
 'ORD10237' 'ORD10302' 'ORD10417' 'ORD10254' 'ORD10177' 'ORD10093'
 'ORD10110' 'ORD10281' 'ORD10339' 'ORD10072' 'ORD10162' 'ORD10333'
 'ORD10270' 'ORD10440' 'ORD10338' 'ORD10092' 'ORD10081' 'ORD10410']
OrderDate ['30-01-2024' '29-12-2024' '27-08-2024' '30-06-2024' '18-01-2024'
 '13-07-2024' '17-06-2024' '06-07-2024' '30-08-2024' '03-04-2024'
 '19-12-2024' '16-06-2024' '02-02-2024' '28-12-2024' '17-08-2024'
 '24-03-2024' '19-08-2024' '29-11-2024' '19-04-2024' '16-02-2024'
 '28-08-2024' '10-06-2024' '04-12-2024' '12-04-2024' '04-10-2024'
 '15-11-2024' '08-11-2024' '27-11-2024' '17-10-2024' '20-08-2024'
 '16-10-2024' '21-08-2024' '26-08-2024' '02-10-2024' '08-02-2024'
 '07-09-2024' '21-06-2024' '14-04-2024' '09-07-2024' '26-03-2024'
 '17-07-2024' '18-05-2024' '13-02-2024' '03-11-2024' '27-12-2024'
 '09-06-2024' '25-01-2024' '01-05-2024' '05-10-2024' '18-04-2024'
 '30-11-2024' '18-08-2024' '24-04-2024' '21-03-2024' '25-09-2024'
 '05-02-2024' '08-05-2024' '09-09-2024' '15-09-2024' '22-07-2024'
 '16-05-2024' '20-01-2024' '17-02-2024' '28-03-2024' '11-10-2024'
 '21-10-2024' '02-06-2024' '02-07-2024' '18-10-2024' '22-10-2024'
 '01-10-2024' '25-10-2024' '22-11-2024' '09-08-2024' '11-12-2024'
 '20-04-2024' '11-03-2024' '13-04-2024' '22-02-2024' '03-10-2024'
 '11-01-2024' '27-04-2024' '16-11-2024' '01-08-2024' '31-10-2024'
 '24-10-2024' '16-12-2024' '15-12-2024' '10-09-2024' '23-06-2024'
 '05-11-2024' '03-06-2024' '29-03-2024' '13-10-2024' '23-10-2024'
 '25-07-2024' '26-04-2024' '21-05-2024' '24-05-2024' '17-04-2024'
 '14-09-2024' '09-03-2024' '24-08-2024' '13-09-2024' '01-04-2024'
 '28-04-2024' '17-01-2024' '19-02-2024' '28-01-2024' '31-03-2024'
 '04-11-2024' '27-09-2024' '14-11-2024' '02-11-2024' '21-04-2024'
 '05-08-2024' '19-10-2024' '06-08-2024' '25-03-2024' '20-02-2024'
 '08-01-2024' '18-03-2024' '02-03-2024' '25-06-2024' '26-06-2024'
 '22-12-2024' '07-06-2024' '10-04-2024' '25-02-2024' '11-02-2024'
 '25-08-2024' '30-05-2024' '08-08-2024' '04-06-2024' '28-10-2024'
 '20-07-2024' '25-12-2024' '16-03-2024' '16-04-2024' '02-01-2024'
 '08-03-2024' '30-09-2024' '09-01-2024' '29-05-2024' '10-01-2024'
 '18-02-2024' '07-08-2024' '07-10-2024' '05-03-2024' '02-08-2024'
 '13-12-2024' '04-01-2024' '19-09-2024' '06-11-2024' '23-12-2024'
 '26-05-2024' '11-08-2024' '12-02-2024' '01-12-2024' '23-08-2024'
 '12-06-2024' '04-05-2024' '12-01-2024' '28-05-2024' '07-02-2024'
 '08-12-2024' '10-10-2024' '29-04-2024' '03-12-2024' '21-02-2024'
 '06-02-2024' '07-05-2024' '31-12-2024' '03-01-2024' '28-06-2024'
 '10-12-2024' '13-03-2024' '07-04-2024' '17-12-2024' '03-07-2024'
 '26-11-2024' '23-04-2024' '20-03-2024' '31-08-2024' '08-04-2024'
 '18-09-2024' '20-11-2024' '05-12-2024' '18-12-2024' '26-09-2024'
 '01-02-2024' '27-05-2024' '25-04-2024' '24-07-2024' '22-08-2024'
 '11-11-2024' '19-07-2024' '12-08-2024' '19-03-2024' '21-01-2024'
 '04-04-2024' '31-07-2024' '31-01-2024' '29-08-2024' '27-02-2024'
 '07-01-2024' '02-12-2024' '10-07-2024' '15-02-2024' '06-10-2024'
 '23-01-2024' '09-10-2024' '29-10-2024' '31-05-2024' '23-11-2024'
 '26-01-2024' '01-07-2024' '16-09-2024' '14-10-2024' '22-06-2024'
 '24-01-2024' '18-11-2024' '06-05-2024' '03-03-2024' '04-03-2024'
 '14-06-2024' '09-05-2024' '11-05-2024' '30-04-2024' '17-03-2024'
 '11-06-2024' '21-09-2024' '09-02-2024' '30-10-2024' '19-06-2024'
 '04-08-2024' '20-05-2024' '04-07-2024' '22-01-2024' '15-07-2024'
 '22-04-2024' '26-10-2024' '27-01-2024' '05-01-2024' '28-07-2024'
 '14-05-2024' '23-07-2024' '08-07-2024' '03-09-2024' '15-05-2024'
 '06-03-2024' '10-11-2024' '04-09-2024' '14-12-2024' '10-05-2024'
 '28-02-2024' '03-02-2024' '15-08-2024' '08-10-2024' '21-07-2024'
 '07-12-2024' '16-01-2024' '23-02-2024' '04-02-2024']
CustomerID ['CUST2295' 'CUST2330' 'CUST2016' 'CUST2086' 'CUST2224' 'CUST2107'
 'CUST2306' 'CUST2241' 'CUST2169' 'CUST2052' 'CUST2249' 'CUST2092'
 'CUST2293' 'CUST2237' 'CUST2012' 'CUST2108' 'CUST2178' 'CUST2099'
 'CUST2094' 'CUST2041' 'CUST2171' 'CUST2116' 'CUST2359' 'CUST2321'
 'CUST2246' 'CUST2027' 'CUST2329' 'CUST2149' 'CUST2200' 'CUST2106'
 'CUST2208' 'CUST2189' 'CUST2334' 'CUST2278' 'CUST2260' 'CUST2234'
 'CUST2093' 'CUST2303' 'CUST2272' 'CUST2252' 'CUST2032' 'CUST2347'
 'CUST2112' 'CUST2165' 'CUST2348' 'CUST2268' 'CUST2164' 'CUST2370'
 'CUST2055' 'CUST2066' 'CUST2010' 'CUST2363' 'CUST2132' 'CUST2115'
 'CUST2034' 'CUST2159' 'CUST2113' 'CUST2318' 'CUST2011' 'CUST2087'
 'CUST2340' 'CUST2255' 'CUST2064' 'CUST2071' 'CUST2173' 'CUST2323'
 'CUST2286' 'CUST2313' 'CUST2181' 'CUST2146' 'CUST2126' ' CUST2003 '
 'CUST2310' 'CUST2353' 'CUST2031' 'CUST2020' 'CUST2063' 'CUST2207'
 'CUST2216' 'CUST2078' 'CUST2035' 'CUST2015' 'CUST2129' 'CUST2201'
 'CUST2322' 'CUST2046' 'CUST2026' 'CUST2163' 'CUST2197' 'CUST2141'
 'CUST2185' 'CUST2360' 'CUST2084' 'CUST2104' 'CUST2065' 'CUST2192'
 'CUST2214' 'CUST2005' 'CUST2110' 'CUST2367' 'CUST2352' 'CUST2040'
 ' CUST2119 ' 'CUST2100' 'CUST2280' 'CUST2253' 'CUST2044' 'CUST2202'
 'CUST2125' 'CUST2140' 'CUST2366' 'CUST2369' 'CUST2250' 'CUST2008'
 'CUST2301' 'CUST2014' 'CUST2228' 'CUST2056' 'CUST2001' 'CUST2358'
 'CUST2232' 'CUST2059' 'CUST2043' 'CUST2160' 'CUST2220' 'CUST2186'
 'CUST2090' 'CUST2219' 'CUST2335' 'CUST2193' 'CUST2162' 'CUST2030'
 'CUST2075' 'CUST2218' 'CUST2076' 'CUST2042' 'CUST2342' 'CUST2033'
 'CUST2152' 'CUST2105' 'CUST2172' 'CUST2128' 'CUST2130' 'CUST2073'
 'CUST2317' 'CUST2351' 'CUST2256' ' CUST2191 ' 'CUST2282' 'CUST2047'
 'CUST2227' 'CUST2155' 'CUST2109' 'CUST2018' 'CUST2009' 'CUST2153'
 'CUST2151' 'CUST2022' 'CUST2133' 'CUST2080' 'CUST2236' 'CUST2333'
 'CUST2283' 'CUST2210' 'CUST2062' 'CUST2085' 'CUST2098' 'CUST2095'
 'CUST2150' 'CUST2204' 'CUST2176' 'CUST2275' 'CUST2315' 'CUST2161'
 'CUST2102' 'CUST2079' 'CUST2314' 'CUST2007' 'CUST2077' 'CUST2157'
 'CUST2309' 'CUST2137' 'CUST2006' 'CUST2336' 'CUST2148' 'CUST2003'
 'CUST2244' 'CUST2243' 'CUST2292' 'CUST2198' 'CUST2147' 'CUST2019'
 'CUST2212' 'CUST2088' 'CUST2145' 'CUST2345' 'CUST2258' 'CUST2039'
 'CUST2331' 'CUST2117' 'CUST2121' 'CUST2338' 'CUST2074' 'CUST2053'
 'CUST2138' 'CUST2135' 'CUST2257' 'CUST2302' 'CUST2229' 'CUST2070'
 ' CUST2110 ' 'CUST2136' 'CUST2344' 'CUST2226' 'CUST2023' 'CUST2288'
 'CUST2263' 'CUST2179' 'CUST2349' 'CUST2354' 'CUST2206' 'CUST2231'
 'CUST2271' 'CUST2037' 'CUST2233' 'CUST2177' 'CUST2024' 'CUST2217'
 'CUST2029' 'CUST2072' 'CUST2143' 'CUST2120' 'CUST2048' 'CUST2175'
 'CUST2341' 'CUST2281' 'CUST2222' 'CUST2196' 'CUST2183' 'CUST2060'
 'CUST2036' 'CUST2190' 'CUST2320' 'CUST2254' 'CUST2319' 'CUST2215'
 'CUST2261' 'CUST2091' 'CUST2050' 'CUST2144' 'CUST2154' ' CUST2069 '
 'CUST2259' 'CUST2251' 'CUST2166' 'CUST2337' 'CUST2170' 'CUST2054'
 'CUST2194' 'CUST2118' 'CUST2332' 'CUST2045' 'CUST2021' 'CUST2089'
 'CUST2213' 'CUST2277' 'CUST2122' 'CUST2230' 'CUST2279' 'CUST2156'
 'CUST2264' 'CUST2221' 'CUST2158' 'CUST2294' 'CUST2339' 'CUST2297'
 'CUST2184' 'CUST2058' 'CUST2298' 'CUST2101' 'CUST2308' 'CUST2290'
 'CUST2324' 'CUST2269' 'CUST2111' 'CUST2025' 'CUST2004' 'CUST2081'
 'CUST2368' 'CUST2188' 'CUST2325' 'CUST2028' 'CUST2168' 'CUST2284'
 'CUST2114' 'CUST2365' 'CUST2289' 'CUST2356' 'CUST2274' 'CUST2328'
 'CUST2350' 'CUST2069' 'CUST2296' 'CUST2357' 'CUST2123' 'CUST2049'
 'CUST2180' 'CUST2265' 'CUST2300' ' CUST2361 ' 'CUST2299' 'CUST2270'
 'CUST2355' ' CUST2266 ' 'CUST2187' 'CUST2235' ' CUST2070 ' 'CUST2262'
 'CUST2182' 'CUST2362' 'CUST2327' 'CUST2167' 'CUST2057' 'CUST2312'
 'CUST2326' 'CUST2083' 'CUST2225' 'CUST2343' 'CUST2038' 'CUST2013'
 'CUST2203' 'CUST2316' 'CUST2068' 'CUST2276' 'CUST2205' 'CUST2245'
 'CUST2240' 'CUST2291' 'CUST2096' 'CUST2002' 'CUST2139' 'CUST2131'
 ' CUST2239 ' 'CUST2134' 'CUST2097' 'CUST2051' 'CUST2211' 'CUST2124'
 'CUST2195' 'CUST2103' 'CUST2267' 'CUST2067' 'CUST2307' 'CUST2017'
 'CUST2061' 'CUST2364' ' CUST2142 ' 'CUST2273' 'CUST2127' 'CUST2238'
 'CUST2304' 'CUST2346' 'CUST2174' 'CUST2242' 'CUST2285' 'CUST2287'
 'CUST2223' 'CUST2311' 'CUST2082' 'CUST2209' 'CUST2248' 'CUST2199'
 'CUST2247' 'CUST2305']
CustomerName ['Suresh Nair' 'Priya Joshi' 'Kiran Das' 'Karthik Bose' 'Sunita Patel'
 'Amit Chatterjee' 'Sai Mukherjee' 'Amit Malhotra' 'Aadhya Gupta'
 'Krishna Chatterjee' 'Kiran Sharma' 'Vikram Malhotra' 'Priya Menon'
 'Aadhya Das' 'Aditya Sharma' 'Rahul Iyer' 'Deepak Rao' 'Aditya Iyer'
 'Deepak Gupta' 'Aditya Das' 'SAANVI MALHOTRA' 'Vikram Bose'
 'Lakshmi Sharma' 'Vihaan Das' 'Sai Reddy' 'Priya Mukherjee'
 'Rohan Kapoor' 'Diya Bose' 'Sai Rao' 'Manoj Pillai' 'Sanjay Singh'
 'Reyansh Gupta' 'Sneha Patel' 'Manoj Desai' 'Rahul Gupta' 'Meera Kapoor'
 'Aarohi Gupta' 'Reyansh Rao' 'Deepak Menon' 'Deepak Patel' 'Nikhil Bose'
 'Arjun Das' 'Sanjay Bose' 'Ramesh Malhotra' 'Myra Mukherjee'
 'Lakshmi Verma' 'Aarohi Iyer' 'Diya Mukherjee' 'Suresh Chatterjee'
 'Vivaan Patel' 'Anika Gupta' 'Kavya Reddy' 'Aarohi Reddy' 'Riya Verma'
 'Deepak Das' 'Pooja Malhotra' 'Reyansh Reddy' 'POOJA KAPOOR'
 'Gita Chatterjee' 'Riya Pillai' 'Lakshmi Pillai' 'Sneha Verma'
 'Sunita Verma' 'Karthik Menon' 'Karthik Singh' 'Gita Menon' 'Anil Rao'
 'Rahul Verma' 'Rahul Kapoor' 'Sanjay Kapoor' 'Manoj Kapoor'
 'Vikram Reddy' 'Priya Singh' 'Vikram Verma' 'Meera Sharma'
 'Suresh Kapoor' 'Ravi Verma' 'Myra Sharma' 'Anika Menon' 'Rohan Sharma'
 'Ananya Rao' 'Kiran Gupta' 'Aditya Menon' 'Manoj Singh' 'Rohan Malhotra'
 'Diya Joshi' 'Priya Sharma' 'Amit Mukherjee' 'Anil Bose' 'Aarohi Verma'
 'Sneha Iyer' 'Karthik Joshi' 'Nikhil Joshi' 'Sai Bose' 'Kiran Joshi'
 'Deepak Iyer' 'Myra Gupta' 'Divya Rao' 'Sai Desai' 'Myra Desai'
 'Reyansh Patel' 'Ananya Menon' 'Ananya Chatterjee' 'Arjun Gupta'
 'KAVYA DAS' 'Sanjay Menon' 'Vihaan Pillai' 'Suresh Malhotra'
 'Diya Chatterjee' 'Aarohi Chatterjee' 'Nikhil Chatterjee' 'Ravi Patel'
 'Ananya Nair' 'Deepak Desai' 'Vikram Mukherjee' 'Sneha Bose'
 'Kiran Patel' 'Kiran Reddy' 'Gita Kapoor' 'Vivaan Pillai' 'Pooja Kumar'
 'Vivaan Verma' 'Anika Rao' 'Sanjay Verma' 'Sunita Kapoor' 'Sai Patel'
 'Nikhil Pillai' 'Vivaan Iyer' 'Manoj Reddy' 'Arjun Desai'
 'Manoj Chatterjee' 'Nikhil Das' 'Sunita Sharma' 'Vikram Kumar'
 'Ishaan Singh' 'Sunita Joshi' 'Divya Nair' 'Rohan Das' 'unknown'
 'Aadhya Verma' 'Ramesh Gupta' 'Nikhil Desai' 'Ravi Singh' 'Ishaan Gupta'
 'Priya Das' 'Riya Kapoor' 'Riya Chatterjee' 'Vikram Patel' 'Divya Verma'
 'Aditya Desai' 'Ishaan Nair' 'Divya Iyer' 'Neha Kumar' 'Ravi Reddy'
 'Ishaan Reddy' 'Diya Nair' 'Meera Patel' 'Saanvi Patel' 'Sneha Pillai'
 'Reyansh Sharma' 'Pooja Reddy' 'Saanvi Verma' 'Kavya Bose' 'Rahul Singh'
 'Manoj Nair' 'Kavya Verma' 'Aadhya Mukherjee' 'Ishaan Kumar'
 'Meera Pillai' 'Sunita Malhotra' 'Nikhil Nair' 'Divya Joshi'
 'Diya Sharma' 'Sai Pillai' 'Neha Chatterjee' 'Nikhil Menon' 'Saanvi Rao'
 'Krishna Reddy' 'Ishaan Malhotra' 'Krishna Patel' 'Ishaan Rao'
 'Amit Kumar' 'Aarohi Patel' 'Priya Pillai' 'Manoj Sharma' 'Pooja Desai'
 'Diya Das' 'Suresh Singh' 'Ananya Iyer' 'Vikram Gupta' 'Meera Gupta'
 'Sunita Singh' 'Riya Malhotra' 'Amit Iyer' 'Vikram Iyer' 'Aarav Nair'
 'Vikram Das' 'Sai Chatterjee' 'Anika Kumar' 'Sai Singh' 'Rahul Menon'
 'Sai Menon' 'Rahul Sharma' 'REYANSH SHARMA' 'Priya Desai'
 'Deepak Mukherjee' 'Vihaan Mukherjee' 'Anika Singh' 'Sai Kumar'
 'Meera Iyer' 'SUNITA DAS' 'Ananya Sharma' 'Divya Menon' 'Vikram Kapoor'
 'Krishna Mukherjee' 'Manoj Kumar' 'Gita Kumar' 'Aarav Das' 'Sai Kapoor'
 'Vihaan Reddy' 'Myra Chatterjee' 'Sanjay Mukherjee' 'Reyansh Singh'
 'Nikhil Singh' 'Anil Malhotra' 'Vihaan Menon' 'Priya Malhotra'
 'Ananya Reddy' 'Aadhya Rao' 'Aditya Nair' 'Reyansh Kapoor' 'Meera Nair'
 'Gita Sharma' 'RIYA VERMA' 'Nikhil Kapoor' 'Sneha Singh' 'Rohan Kumar'
 'Divya Sharma' 'Kiran Verma' 'Sunita Rao' 'Rohan Menon' 'Ravi Kapoor'
 'Divya Malhotra' 'Ishaan Chatterjee' 'Vikram Joshi' 'Divya Desai'
 'Arjun Kumar' 'Gita Patel' 'Myra Nair' 'Priya Reddy' 'Ananya Singh'
 'Arjun Nair' 'Riya Patel' 'Pooja Pillai' 'Vihaan Bose' 'Pooja Patel'
 'Diya Pillai' 'Suresh Iyer' 'Vikram Pillai' 'Sunita Chatterjee'
 'RAHUL MENON' 'Kavya Sharma' 'Manoj Joshi' 'Arjun Reddy' 'Diya Desai'
 'Arjun Iyer' 'Lakshmi Malhotra' 'Suresh Sharma' 'Myra Das' 'Krishna Bose'
 'Deepak Kapoor' 'Ishaan Joshi' 'Suresh Kumar' 'Manoj Malhotra'
 'Ishaan Verma' 'Amit Nair' '-' 'Deepak Singh' 'Pooja Nair' 'Riya Reddy'
 'Neha Das' 'Pooja Sharma' 'Vikram Nair' 'Ravi Joshi' 'Sneha Menon'
 'VIHAAN DESAI' 'Rahul Chatterjee' 'VIHAAN SINGH' 'Ravi Desai'
 'MANOJ KAPOOR' 'Reyansh Mukherjee' 'SANJAY MENON' 'Sneha Chatterjee'
 'Sneha Kumar' 'Anika Iyer' 'Reyansh Chatterjee' 'Meera Rao' 'Diya Verma'
 'AARAV PILLAI' 'Rohan Bose' 'Suresh Joshi' 'Saanvi Joshi' 'Neha Rao'
 'Pooja Gupta' 'Aarohi Kapoor' 'Pooja Rao' 'DIVYA DESAI' 'Aditya Joshi'
 'ANIKA BOSE' 'Anil Das' 'Riya Menon']
Gender ['Male' 'Female']
City ['Mumbai' 'Bangalore' 'Kolkata' 'Pune' 'Hyderabad' 'Chennai' 'Delhi']
Area ['Dadar' 'Jayanagar' 'Park Street' 'Hinjewadi' 'Kharadi' 'Koramangala'
 'Bandra' 'Secunderabad' 'Kothrud' 'Salt Lake' 'Saket' 'Anna Nagar'
 'Electronic City' 'HSR Layout' 'Madhapur' 'Connaught Place' 'Andheri'
 'Powai' 'Velachery' 'Ballygunge' 'Dwarka' 'Banjara Hills' 'T Nagar'
 'Kukatpally' 'Rohini' 'Adyar' 'Baner' 'Karol Bagh' 'OMR' 'Malad'
 'Indiranagar' 'Whitefield' 'Gachibowli' 'Viman Nagar' 'Howrah']
RestaurantID ['R009' 'R003' 'R007' 'R015' ' R005 ' ' R001 ' 'R002' 'R001' 'R004' 'R012'
 'R006' 'R005' 'R014' 'R013' 'R010' 'R008' 'R011' ' R014 ' ' R012 '
 ' R006 ' ' R013 ' ' R003 ' ' R010 ' ' R015 ' ' R007 ']
RestaurantName ['The Bakers Oven' 'Dragon Wok' 'Sushi Yama' 'Chaat Corner' 'Burger Point'
 'Biryani Blues' 'Pizza Palace' 'Punjabi Tadka' 'Noodle Story'
 'South Spice' 'Healthy Bites' 'Sweet Tooth' 'Kebab Junction'
 'Taco Fiesta' 'Curry House']
Cuisine ['Bakery' 'Chinese' 'Japanese' 'Street Food' 'Fast Food' 'North Indian'
 'Italian' 'South Indian' 'Salads' 'Desserts' 'Mughlai' 'Mexican']
ItemName ['Cupcake' 'Veg Noodles' 'Chicken Ramen' 'Pani Puri' 'Bhel Puri'
 'Cheese Burger' 'Mutton Biryani' 'Pepperoni Pizza' 'Chicken Biryani'
 'Butter Chicken' 'Spring Rolls' 'Chicken Manchurian' 'Idli Sambar'
 'French Fries' 'Vada Pav' 'Croissant' 'Pasta Alfredo' 'California Roll'
 'Quinoa Salad' 'Gulab Jamun' 'Masala Dosa' 'Uttapam' 'Chocolate Cake'
 'Brownie' 'Seekh Kebab' 'Veg Biryani' 'Burrito Bowl' 'Chicken Tacos'
 'Fruit Bowl' 'Paneer Tikka' 'Dal Makhani' 'Nachos' 'Margherita Pizza'
 'Chicken Kebab' 'Caesar Salad' 'Veg Burger' 'Ice Cream Sundae'
 'Mutton Rogan Josh' 'Miso Soup']
CategoryName ['Desserts' 'Noodles' 'Main Course' 'Street Food' 'Burger' 'Pizza'
 'Starters' 'Breakfast' 'Sides' 'Bakery' 'Pasta' 'Sushi' 'Salads']
OrderStatus ['Cancelled' 'Delivered' 'Returned']
PaymentMode ['Wallet' 'DebitCard' 'CreditCard' 'UPI' 'Cash On Delivery']
PaymentStatus ['Failed' 'Paid' 'Refunded']

In [ ]:
df[num_cols].describe()

,Age,RestaurantRating,Quantity,UnitPrice,TotalAmount,DistanceKM,DeliveryTimeMin,FoodRating,DeliveryRating
count,503.000000,503.000000,503.000000,503.000000,503.000000,503.000000,503.000000,503.000000,503.000000
mean,38.868787,4.110220,3.021869,177.007117,578.302724,7.978728,46.351889,4.091451,4.111332
std,14.382325,0.753214,1.733637,74.720042,397.536604,11.601740,40.451651,0.810530,0.733063
min,-5.000000,-1.000000,-5.000000,50.000000,60.000000,-3.500000,-15.000000,-2.000000,-1.000000
25%,29.000000,4.000000,2.000000,110.000000,260.000000,4.000000,28.000000,4.000000,4.000000
50%,39.000000,4.100000,3.000000,180.000000,480.000000,7.500000,43.000000,4.000000,4.000000
75%,48.000000,4.300000,4.000000,220.000000,840.000000,11.050000,58.500000,5.000000,5.000000
max,150.000000,11.000000,5.000000,350.000000,3086.240000,250.000000,500.000000,6.000000,6.000000